name: Daily build

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  ubuntu-build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Get daily docker version
        id: version
        run: echo "::set-output name=version::$(date +'%Y-%m-%d')"
#      - name: Get project version
#        id: project-version
#        run: |
#          SHORT_VERSION=$((grep -w "version" | cut -d= -f2 | cut -d- -f1) < gradle.properties)
#          DIST_VERSION=$((grep -w "version" | cut -d= -f2) < gradle.properties)
#          CODE_NAME=$((grep -w 'codeName' | cut -d= -f2) < gradle.properties)
#          RELEASE_VERSION=$DIST_VERSION-$CODE_NAME
#          echo "::set-output name=version::$RELEASE_VERSION"
#          echo "::set-output name=sversion::$SHORT_VERSION"
      - name: Build with Maven
        run: |
          mvn --version
          mvn -s settings.xml clean install -Dmaven.test.skip=true
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
          TEST_MODE_ACTIVE: true
      - name: Archive Ballerina ZIP
        uses: actions/upload-artifact@v2
        with:
          name: Ballerina ZIP
          path: ballerina/target/ballerina-1.2.*.zip

